### ISSUE TITLE
disk cache path needs commenting to give correct path example

### ISSUE THREAD

**Issue by stylemessiah** [diladele/squid3-windows#27]
I spent ages trying to get my disk cache going on d drive.

Previously using squidnt and just used format similar to:

cache_dir d:/squid/cache 3000 16 256 (i.e. only change from msdos paths is forward slashes)

After a nice email from Raf, with a link to the relevant page, i came to learn that the correct format is:

cache_dir aufs /cygdrive/d/squid/cache 3000 16 256

Can you please update the comment line in the default squid.conf to reflect this

Something like:

#uncomment the line below to enable disk caching - path format is /cygdrive/<drive letter>/path to cache folder <options>
#cache_dir aufs /cygdrive/d/squid/cache 3000 16 256

It will save Raf having to direct people to a link to a page that i couldnt find myself :)

**Comment by ea-at-diladele-com** [comment]
Resolved. Please check out the new installer and close the issue. Thank you!
