### ISSUE TITLE
Default installer path

### ISSUE THREAD

**Issue by stylemessiah** [diladele/squid3-windows#28]
The current default install path is in c:\program files. This is not ideal as any edit to the squid.conf (or any editable file in the program files path for that matter) raises a permissions error when trying to save (due to program files privileged path protection), forcing you to save it elsewhere, then you have to navigate to that folder and manually move it, overwriting the existing file....its a long way to do things if you need to edit squid.conf (or any other editable file under program files) regularly, mostly during testing. Under a path of c:\squid, theres no such penalty, a save actually saves in one easy click :)

I always install to the root of the drive, but others may not even think about this when installing. Being a ported linux program, its already got enough path quirks, program files doesnt need to be mixed in :)

Cheers and thanks for the squid build!

**Comment by ea-at-diladele-com** [comment]
Changed. Please check out the new installer and close the issue. Thank you!
