### ISSUE TITLE
Installing on Windows server 2012

### ISSUE THREAD

**Issue by godzillad** [diladele/squid3-windows#30]
While installing the msi on Windows Server 2012, I get the error message "This product required Microsoft .Net 2.0 to be installed on this machine." Windows server 2012 comes with .net 4.5 pre installed.

**Comment by ea-at-diladele-com** [comment]
The tray application requires .net 2.0, so you have to install it in addition to .net.4.5. On windows .net versions are not compatible intefacewise.

So please install .net2.0 from http://www.microsoft.com/en-gb/download/details.aspx?id=1639 
Thank you!

**Comment by ea-at-diladele-com** [comment]
I would appreciate if you could close the issue in case the above comment solved your problem. Thank you!

**Comment by ea-at-diladele-com** [comment]
By the way, did you try adding the following line to the configuration file?
max_filedescriptors 3000

This should increase the maximum number of file descriptors without recompilation.

Thank you!

**Comment by ea-at-diladele-com** [comment]
I have enabled rebinding of .net 2 to .net 4, which is default for 2012. in the new release (coming in the next couple of days) you will be able to install squid on win 2012 without installation of .net 2.

Thank you very much for reporting this! And sorry for the trouble.

**Comment by ra-at-diladele-com** [comment]
Just released 3.5.5. Closing...
