### ISSUE TITLE
binary to include --enable-heap-replacement in next version of squid for windows

### ISSUE THREAD

**Issue by saishwetoe** [diladele/squid3-windows#32]

**Comment by ea-at-diladele-com** [comment]
This is a deprecated option, please see http://wiki.squid-cache.org/SquidFaq/InnerWorkings#What_does_--enable-heap-replacement_do.3F 
"This option is only relevant for Squid-2. It has been replaced in Squid-3 by --enable-removal-policies=heap"

The next release will contain binaries compiled with --enable-removal-policies=heap

**Comment by ra-at-diladele-com** [comment]
Fixed in the latest build available on site. Closing.
