### ISSUE TITLE
FTP over HTTP problem

### ISSUE THREAD

**Issue by adeit** [diladele/squid3-windows#33]
When using FTP over HTTP (ftp://... url in regular browser), Squid is extremely slow to generate each folder display page.

The reason can be found in cache.log : squid tries to get its graphical icons (folder.png, arrow_up.png, ...) from the remote FTP server currently accessed, instead of the local machine. It mixes local path and remote host.

For instance (from cache.log) :
(...)
2015/05/11 21:46:29 kid1| internalStart: unknown request:
GET /squid-internal-static/icons/silk/folder.png HTTP/1.1
Host: ftp.skynet.be
(...)

Each time an icon is needed to compose the page, the problem occurs. The resulting page does not contain the icon, and the generation is extremely slow.

Adding parameter "short_icon_urls off" to squid.conf only partially fixes the problem : icons are back in the displayed page, but generation is still slow and errors in cache.log remain. For some reason squid continues to mix local path and remote host, but manages however to get the icon(s) in the end... ?

**Comment by ea-at-diladele-com** [comment]
This is a squid problem that was fixed recently (not the installer one):

On Thu, 21-May-2015 at 21:54:21 +1200, Amos Jeffries wrote:
 > >> This is http://bugs.squid-cache.org/show_bug.cgi?id=4132. Thank you for
 > >> the patch a slightly tweaked version (no extra debugs message) is now
 > >> applied to Squid-4 and should be in the next releases.


It will be included in the next release of the installer as well.

**Comment by ra-at-diladele-com** [comment]
Just released 3.5.5. Closing...
