### ISSUE TITLE
Service status feedback and resiliency improvement suggestion

### ISSUE THREAD

**Issue by adeit** [diladele/squid3-windows#35]
Squid service (Diladele.Squid.Service.exe) appears to be a launcher and does not reflect the health status of the squid processes. If for some reason one of the squid process dies (or even if they all die), Squid service keeps a "running" status and does not reflect the proxy state.

It should probably be better if Squid service launcher periodically polled the squid processes responsiveness / status, to be able either to try to restart it/them or at least to reflect their state to the operating system (and monitoring agents if any) by stopping itself (and remaining squid processes if any) in case of problem. At least OS or third party jobs should be able to restart it.

**Comment by ea-at-diladele-com** [comment]
It already tries to restart them in case it cannot find any processes with name "squid" in a running state.

For errors please see the system log using event viewer.

Thank you!

**Comment by adeit** [comment]
You are right. I did not wait long enough to see them "respawn".
Thanks for your feedback and sorry for my irrelevant comment.
I will now close this "non-issue" :-)
