### ISSUE TITLE
MSI - no upgrade

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/squid3-windows#36]
You MSI haven't upgrade option, and rolled back installation without any reasonable reasons and errors diagnostics.

**Comment by ea-at-diladele-com** [comment]
Could it be that the firewall is disabled? I will have a look at this and try to fix asap.

**Comment by ea-at-diladele-com** [comment]
As a workaround, please enable the firewall and try to rerun the installation. Thank you!

**Comment by ea-at-diladele-com** [comment]
I have fixed in the latest sources.

**Comment by ra-at-diladele-com** [comment]
Ok seems to be correctly installing now (the fw is enabled);
