### ISSUE TITLE
Crash of the tray on windows 2008 R2 64

### ISSUE THREAD

**Issue by ea-at-diladele-com** [diladele/squid3-windows#38]
Installed 3.5.5 on Server 2008 R2 x64. At login SquidTray crashes and windows gives the following minimal output. I can live without SquidTray anyway but thought I should report it.

 I did have 3.5.1 working previously.
 MarkJ
 -------
 Description:
   Stopped working
 Problem signature:
   Problem Event Name: CLR20r3
   Problem Signature 01: diladele.squid.tray.exe
   Problem Signature 02: 1.0.0.0
   Problem Signature 03: 55715464
   Problem Signature 04: mscorlib
   Problem Signature 05: 2.0.0.0
   Problem Signature 06: 53a11de1
   Problem Signature 07: 123f
   Problem Signature 08: 5f
   Problem Signature 09: System.IO.FileNotFoundException
   OS Version: 6.1.7601.2.1.0.272.7
   Locale ID: 3081

**Comment by ea-at-diladele-com** [comment]
Thank you for reporting! Will be fixed in the next release

**Comment by ra-at-diladele-com** [comment]
3.5.6 is on site - squid.diladele.com
