### ISSUE TITLE
Default install location Z drive

### ISSUE THREAD

**Issue by todd-bowles-onthehouse** [diladele/squid3-windows#41]
I have an m3.medium EC2 instance in AWS that I'm trying to automatically (i.e. non-interactively) install Squid on.

This instance has an ephemeral drive automatically mapped to Z.

Via the MSI, Squid insists on installing to Z.

It does this regardless of whether I override ROOTDRIVE, INSTALLDIR, TARGETFOLDER or any of the other variables that you can set via MSIEXEC.

Any ideas?

**Comment by ea-at-diladele-com** [comment]
The installer is written in WiX, by default it installs the application to whichever drive has the most available space. 
Did you try overriding TARGETDIR?

**Comment by todd-bowles-onthehouse** [comment]
Hmmmm, that may have been the only variable I failed to change.

I will investigate this and get back to you.

Thank you for the help.

**Comment by ea-at-diladele-com** [comment]
Were you successful? Did it work?

Thank you!
-ea

**Comment by todd-bowles-onthehouse** [comment]
I have not had a chance to return to this. I settled for using an instance with no ephemeral storage.

I have this in my backlog to investigate, so I will add more information when I investigate.

**Comment by ra-at-diladele-com** [comment]
3.5.6 is on site - squid.diladele.com

**Comment by todd-bowles-onthehouse** [comment]
Thank you. I have had a chance to look into this again, and overriding the ROOTDRIVE appears to correctly install to the drive I specify, rather than Z drive.

I tested using 3.5.10.
