### ISSUE TITLE
Failes to create cache dir with 2015/10/13 22:40:58| assertion failed: Kid.cc:45: "cpid > 0"

### ISSUE THREAD

**Issue by JouMxyzptlk** [diladele/squid3-windows#46]
The squid package (3.5.9 and 3.5.10 tried) installs itself to F:\squid.
It is automatically chosen and fine, it is the biggest drive.
It seems to work too.
Then I add:
cache_dir aufs /cygdrive/f/Squid/var/squid/cache 93000 16 256
Then I am supposed to run (just as I am used on Linux squid):
squid -z
Result in the log file:
2015/10/13 22:47:06| assertion failed: Kid.cc:45: "cpid > 0"

The variant:
cache_dir aufs /cygdrive/f/Squid/var/squid/cache 13000 16 256
does not work either, squid -z does not create the directories.

F:\Squid\bin>squid -z -f /cygdrive/f/Squid/etc/squid/squid.conf

doesn't do what it should too...

This is the cache.log from trying with 3.5.9:

2015/10/13 22:48:38 kid1| Set Current Directory to /var/cache/squid
2015/10/13 22:48:38 kid1| Starting Squid Cache version 3.5.9-20150922-r13918 for x86_64-unknown-cygwin...
2015/10/13 22:48:38 kid1| Service Name: squid
2015/10/13 22:48:38 kid1| Process ID 7348
2015/10/13 22:48:38 kid1| Process Roles: worker
2015/10/13 22:48:38 kid1| With 3200 file descriptors available
2015/10/13 22:48:38 kid1| Initializing IP Cache...
2015/10/13 22:48:38 kid1| parseEtcHosts: /etc/hosts: (2) No such file or directory
2015/10/13 22:48:38 kid1| DNS Socket created at [::], FD 5
2015/10/13 22:48:38 kid1| DNS Socket created at 0.0.0.0, FD 6
2015/10/13 22:48:38 kid1| Adding nameserver 8.8.8.8 from squid.conf
2015/10/13 22:48:38 kid1| Adding nameserver 208.67.222.222 from squid.conf
2015/10/13 22:48:38 kid1| Logfile: opening log daemon:/var/log/squid/access.log
2015/10/13 22:48:38 kid1| Logfile Daemon: opening log /var/log/squid/access.log
2015/10/13 22:48:38 kid1| WARNING: no_suid: setuid(0): (22) Invalid argument
2015/10/13 22:48:38 kid1| Store logging disabled
2015/10/13 22:48:38 kid1| Swap maxSize 13312000 + 262144 KB, estimated 1044164 objects
2015/10/13 22:48:38 kid1| Target number of buckets: 52208
2015/10/13 22:48:38 kid1| Using 65536 Store buckets
2015/10/13 22:48:38 kid1| Max Mem  size: 262144 KB
2015/10/13 22:48:38 kid1| Max Swap size: 13312000 KB
2015/10/13 22:48:38 kid1| ERROR: /cygdrive/f/Squid/var/squid/cache: (2) No such file or directory
FATAL: 	Failed to verify one of the swap directories, Check cache.log
	for details.  Run 'squid -z' to create swap directories
	if needed, or if running Squid for the first time.
Squid Cache (Version 3.5.9-20150922-r13918): Terminated abnormally.
CPU Usage: 0.061 seconds = 0.015 user + 0.046 sys
Maximum Resident Size: 1222656 KB
Page faults with physical i/o: 4869

But the directory IS THERE... (copy paste from explorer):
F:\Squid\var\cache\squid
There is also no security problem for file access, since the whole drive is set to be read-writable be "everyone".

OS is Windows 10 x64, other cygwin "portings", i.e. collect program with the dependencies work fine.

I cannot see why cache_dir failes, without that directive it works, but is is completely useless without a disk cache.

**Comment by ra-at-diladele-com** [comment]
Please see http://docs.diladele.com/faq/squid/cache_squid_windows.html especially the "run the squid terminal shortcut on your desktop as administrator and perform the following commands."

**Comment by JouMxyzptlk** [comment]
Thank you.
Finally my usual config I am used on linux with
cache_replacement_policy heap LFUDA
cache_dir aufs /cygdrive/f/Squid/var/cache/squid 150000 32 256
works as expected.

**Comment by SoreGums** [comment]
I don;t have a shortcut on my desktop - what is the contents on the shortcut?
thanks
