### ISSUE TITLE
**security risks** due to outdated OpenSSL Cygwin DLL's included in the Diladele MSI 

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/squid3-windows#54]
The latest MSI Installer for Squid 3.5.11 for Windows built with Cygwin,
dated Nov 9, 2015,
http://packages.diladele.com/squid/3.5.11/squid.msi
contains (like the previous packages)
outdated OpenSSL CygWin DLL's,
especially the files cygcrypto_1.0.0.dll and cygssl_1.0.0.dll, which are
dated February 2015,
corresponding to OpenSSL version 1.0.1k:

But this OpenSSL version 1.0.1k has several security flaws.
The current version is 1.0.1r so there are been *seven *OpenSSL security
releases between your version and the current OpenSSL one.

See the security changes in the URL below:
https://openssl.org/news/cl101.txt

For your information you can download the latest CygWin OpenSSL DLL's
from CygWin mirrors like this one:

ftp://bo.mirror.garr.it/mirrors/sourceware.org/cygwin/x86_64/release/openssl/libopenssl100/

As a result, would be possible to always include in the next Diladele
Squid MSI packages for Windows,
the latest OpenSSL Cygwin libraries, in order to keep (for instance) the
security of HTTPS proxies ?

**Comment by ea-at-diladele-com** [comment]
Correct me if I'm wrong here, but current Cygwin is based on openssl 1.0.2f.
I am closing this bug for now, we rely on Cygwin to update security related issues.
