### ISSUE TITLE
negotiate_kerberos_auth for Windows Server member of AD

### ISSUE THREAD

**Issue by gitdevmod** [diladele/squid3-windows#55]
Hi,
I supposed installing squid on Windows member of AD will not need kerberos configuration, is this possible ?

2015/12/15 15:48:38 kid1| Starting new negotiateauthenticator helpers...
2015/12/15 15:48:38 kid1| helperOpenServers: Starting 1/10 'negotiate_kerberos_auth' processes
2015/12/15 15:48:38 kid1| WARNING: no_suid: setuid(0): (22) Invalid argument
2015/12/15 15:48:38| negotiate_kerberos_auth: ERROR: krb5_kt_start_seq_get: Key table file '/etc/krb5.keytab' not found
2015/12/15 15:48:38| negotiate_kerberos_auth: ERROR: krb5_read_keytab: Key table file '/etc/krb5.keytab' not found
2015/12/15 15:48:38 kid1| ERROR: Negotiate Authentication validating user. Result: {result=BH, notes={message: received
 type 1 NTLM token; }}

auth_param negotiate program /cygdrive/c/squid/lib/squid/negotiate_kerberos_auth
auth_param negotiate children 10
auth_param negotiate keep_alive on
acl password proxy_auth REQUIRED

Thanks in advance

**Comment by ea-at-diladele-com** [comment]
According to the squid mailing list the negotiate_kerberos_auth helper is for Unix only.

You can try to put the corresponding files into the "<squidinstallation>/etc" directory, but this functionality was never tested. More information how you can generate these files, please see 
http://www.itadmintools.com/2011/07/creating-kerberos-keytab-files.html

**Comment by gitdevmod** [comment]
I tried to generate a keytab file with ktpass but without success. Thanks your response.
