### ISSUE TITLE
what are config options

### ISSUE THREAD

**Issue by daniel-lucio** [diladele/squid3-windows#57]
Can we have the output of squid -v
(sorry, not windows here to do it by myself)

**Comment by ryonm** [comment]
As of 3.5.12 MSI:

C:\Squid\bin>squid -v
Squid Cache: Version 3.5.12-20151218-r13964
configure options:  '--bindir=/bin/squid' '--sbindir=/usr/sbin/squid' '--sysconfdir=/etc/squid' '--datadir=/usr/share/squid' '--libexecdir=/usr/lib/squid' '--disable-strict-error-checking' '--with-logdir=/var/log/squid' '--with-swapdir=/var/cache/squid' '--with-pidfile=/var/run/squid.pid' '--enable-ssl' '--enable-delay-pools' '--enable-ssl-crtd' '--enable-icap-client' '--enable-esi' '--disable-eui' '--localstatedir=/var/run/squid' '--sharedstatedir=/var/run/squid' '--datarootdir=/usr/share/squid' '--enable-disk-io=AIO,Blocking,DiskThreads,IpcIo,Mmapped' '--enable-auth-basic=DB,LDAP,NCSA,POP3,RADIUS,SASL,SMB,fake,getpwnam' '--enable-auth-ntlm=fake' '--enable-auth-negotiate=kerberos,wrapper' '--enable-external-acl-helpers=LDAP_group,SQL_session,eDirectory_userip,file_userip,kerberos_ldap_group,session,time_quota,unix_group,wbinfo_group' '--with-openssl' '--with-filedescriptors=65536' '--enable-removal-policies=lru,heap'


Build options are also available in:

http://docs.diladele.com/tutorials/build_squid_windows/index.html
