### ISSUE TITLE
Squid msi 3.5.14 slow internet loading(waiting for connection issue)?

### ISSUE THREAD

**Issue by j19861986** [diladele/squid3-windows#59]
I have tried your version 3.5.14 of msi at github squid link, it is slow when loading websites, it waits for connection on websites for quite some time.
3.5.12 on my other pc, it doesn't wait long till it loads.
Is there a problem on 3.5.14 (on github site link) loading websites?

**Comment by j19861986** [comment]
The long wait time, could be that it doesn't try dns v4, and trying dns v6 first time.
Gotta check that at home later.

**Comment by ea-at-diladele-com** [comment]
Could be dns. 
This is not related to the installer per say, we did not change anything between 12 and 14, only recompiled squid.
