### ISSUE TITLE
Isses getting it to work with cache_dir

### ISSUE THREAD

**Issue by Chris763454357** [diladele/squid3-windows#60]
I installed this, and put in the port on the proxy. I then tried to setup the cache (to store it on my pc)
I have a folder: c:/squidcachedir

But anytime I uncommment this line and restart the service the proxy does not work:
cache_dir aufs /cygdrive/c/squidcachedir 3000 16 256

I tried re-installing without any luck.

**Comment by ea-at-diladele-com** [comment]
Please see
http://docs.diladele.com/faq/squid/cache_squid_windows.html 
Hope this helps

**Comment by Chris763454357** [comment]
Thanks, but I have already tried that solution a few times.

**Comment by ea-at-diladele-com** [comment]
you are sure you used squid terminal to run squid -z, right?
which version of the product r u using?

**Comment by Chris763454357** [comment]
Yeah I am running that command in the terminal window (the squid.exe in the bin directory).

Version: Squid 3.5.15 for Microsoft Windows

**Comment by ea-at-diladele-com** [comment]
when you run squid -z, does it create subfolders in your c:/squidcachedir?

**Comment by Chris763454357** [comment]
No, Iv'e yet to see any folders in my cache dir.

My cache.log also generates:
assertion failed: Kid.cc:45: "cpid > 0"

**Comment by Chris763454357** [comment]
Oops, this was my fault.... When I installed this there was two icons created on the desktop, the first one was 'Squid Terminal' that was hidden between two other icons, so I only assumed 'Squid Server Tray' was the only shortcut. This appears to be working now, thanks for your time.

**Comment by ea-at-diladele-com** [comment]
Great! Closing it then.
