### ISSUE TITLE
squid -z not creating swap directories

### ISSUE THREAD

**Issue by ayrad** [diladele/squid3-windows#62]
cache_dir config:
`cache_dir aufs /cygdrive/c/Squid/var/cache/squid 3000 16 256`

Nothing happens when running `squid -z`. That folder still empty and the following error is logged:
`2016/05/13 12:09:28 kid1| ERROR: /cygdrive/c/Squid/var/cache/squid/00: (2) No such file or directory
FATAL: 	Failed to verify one of the swap directories, Check cache.log
	for details.  Run 'squid -z' to create swap directories
	if needed, or if running Squid for the first time.
Squid Cache (Version 3.5.19): Terminated abnormally.`

**Comment by ra-at-diladele-com** [comment]
Please see http://docs.diladele.com/faq/squid/cache_squid_windows.html

**Comment by ayrad** [comment]
Ok, just changed the folder to `/cygdrive/c/squidcachedir/cache` and now it works. Thanks

**Comment by leodexe** [comment]
> Please see http://docs.diladele.com/faq/squid/cache_squid_windows.html
What the hell, I can't understand this.

WHERE DO I HAVE TO CREATE THE CYGDRIVER FOLDER?!??!??!??!

Please update these instructions. For some reason, maybe magic, only the first time I launch squid from a fresh install will work. Then after that it will throw this same error and I have to uninstall a reinstall it again. The provided instructions from earlier didn't work for me unless I'm missing something.
