### ISSUE TITLE
missing Squid Terminal (its not in desktop,not in start menu)

### ISSUE THREAD

**Issue by orangpelupa** [diladele/squid3-windows#63]
reading this
https://github.com/diladele/squid3-windows/issues/40

it should be on the desktop. But its nowhere to be found.

what is the shortcut? so i can invoke it manually.

thank you

**Comment by ea-at-diladele-com** [comment]
The main thing is about adding the bin to the PATH variable (my installation is in M:\Squid).
You can create a simple cmd shortcut with the following target.

C:\Windows\System32\cmd.exe /K "color 02 & cd /dM:\Squid\ & set PATH=M:\Squid\bin;%PATH%"
